### PR TITLE
Initial attempt to Install a Job

### PR DESCRIPTION
**Pull request by DLu**
I'm fairly clueless as to how this works but I'd like some feedback before I go too far down this path. My goal is to have the command `rosrun locus_dev_scripts get_bloom_status` run on the build server periodically and the output put somewhere useful.

Problem is I don't know how to test it....

### CODE REVIEW

**Comment by ayrton04** [comment]
I think the only way to test this is to just try to use it for a buildfarm deployment.

**Review by ayrton04 — APPROVED** [review]
We can try a dry run against the build farm

**Comment by paulbovbel** [comment]
How does the script end up on the buildfarm so that it can be 'rosrunnable'?

**Comment by DLu** [comment]
@paulbovbel Good question. Do you think I should add a step to clone the git repo, or should I grab the binary? Don't know what's customary.

**Comment by paulbovbel** [comment]
I think this is why the ros buildfarm stuff is mostly pure python and not catkin-related. You probably don't want to create a chicken-egg situation where you're installing the output of the buildfarm (deb packages) as part of the buildfarm jobs.

**Comment by ayrton04** [comment]
The script just emulates the other doc jobs (e.g., release comparison pages), right, @DLu? I can deploy this tomorrow and see what happens. May need to merge it first, though.

**Comment by ayrton04** [comment]
@DLu I tried a dry run deploy from your branch, and I am getting this:

```
Invoking '/tmp/deploy_ros_buildfarm/venve/bin/generate_bloom_status_job.py http://gitlab.locusbots.io/locusrobotics/ros_buildfarm_config/raw/master/index.yaml --dry-run'

Traceback (most recent call last):
  File "/tmp/deploy_ros_buildfarm/venve/bin/generate_all_jobs.py", line 328, in <module>
    main()
  File "/tmp/deploy_ros_buildfarm/venve/bin/generate_all_jobs.py", line 138, in main
    generate_bloom_status_job(args.config_url, dry_run=not args.commit)
  File "/tmp/deploy_ros_buildfarm/venve/bin/generate_all_jobs.py", line 300, in generate_bloom_status_job
    _check_call(cmd)
  File "/tmp/deploy_ros_buildfarm/venve/bin/generate_all_jobs.py", line 321, in _check_call
    rc = module.main(cmd[1:])
  File "/tmp/deploy_ros_buildfarm/venve/bin/generate_bloom_status_job.py", line 37, in main
    job_config = get_job_config(args, config)
TypeError: get_job_config() takes 1 positional argument but 2 were given
```

**Comment by DLu** [comment]
Ok, I've cleaned this up to match more of the existing structure and to use a script located in this very repo. The script is a modified version of the get_bloom_status script, but without needing git tokens or ros installed on the remote machine. 

I've dry-ran this, but haven't tried a _real_ deploy.

**Review by paulbovbel — APPROVED** [review]
LGTM, though you may need to add github and requests to the setup.py requirements of this package.

**Comment by ayrton04** [comment]
I did a full deploy with this script, and can [confirm](http://build.locusbots.io/job/bloom_status/2/console) that the script is failing to load the `github` module. I'm guessing the same will happen with requests.

**Pull request merged**
